In [2]:
import torch
print(torch.__version__)

2.5.1+cu121


In [7]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: NVIDIA GeForce RTX 4050 Laptop GPU


In [3]:
print(torch.version.cuda)


12.1


In [ ]:
"""tensor is a specialised multi dimension array designed for mathematical and computational efficiancy 

real world examples:
Zero dimension : scaler like 1,2,3,9999

vectors :1D 
sentence embedding 

matrics 2 dimensional tensors 
gray scale images 

3d dimension 
RGB images color images 


4d tensor 
batches of rgb images 

5d tensor 
videos data ->frames combination of frames 



why tensors are useful ?
#.mathematical operations :
tensos enable efficient mathematics computations(addition multiplication , dot product, etc)
neccessary for the neural network 

# representation of real world data 

# efficient computations 
tensors are optimissed for hardware acceleration, allowing computations on GPUs or TPUs,Which are crucial for 
training deep learning models 

Where are tensors used in deep learning ?

data storage 
training data is stored in tensors 

weights and BIases 
the learnable parameters of a neural network are stored as tensors 


matrix operation 

"""

'tensor is a specialised multi dimension array designed for mathematical and computational efficiancy \n\nreal world examples:\n\n\n\n'

In [ ]:
#using empty 
a = torch.empty(2,3,requires_grad=True)  #allocating memeory for specific tensor
print(a)

tensor([[-4.7554e+29,  1.7544e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [9]:
# check type 
print(a.type())

torch.FloatTensor


In [13]:
# using zeros 
b = torch.zeros(3,3)
print(b)
print("type of b tensor is :- ", b.type())


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
type of b tensor is :-  torch.FloatTensor


In [12]:
# using ones 
c = torch.ones(3,1)
print(c)

tensor([[1.],
        [1.],
        [1.]])


In [ ]:
# using rand
d = torch.rand(size=(2,3),requires_grad=True)
print(d)

# here each and everytime whenever you ran the code you got diffrent output.


tensor([[0.6163, 0.4884, 0.2131],
        [0.8815, 0.7318, 0.9218]], requires_grad=True)


In [ ]:
# using seed 
torch.manual_seed(100)    #for reproducibility we use this 
d = torch.rand(size=(2,3),requires_grad=True)
print(d)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]], requires_grad=True)


In [ ]:
# other ways 
tenso = torch.tensor([[1,5,4],[7,4,2]],dtype=float,requires_grad=True)


True


In [51]:
#arange 
print("using arrange:- ",torch.arange(0,10,2))

# using linspace 
print("using linspace:- ",torch.linspace(0,10,10))

# using eye  -> for identity matrix 
print("using eye develpoing idenetity matrix :-\n",torch.eye(3))


# using full when you want all element specifically one element then you use this 
print("using full:-\n ", torch.full((3,2),10))




using arrange:-  tensor([0, 2, 4, 6, 8])
using linspace:-  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye develpoing idenetity matrix :-
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
using full:-
  tensor([[10, 10],
        [10, 10],
        [10, 10]])


In [ ]:
# how to find shape of the tensors 
print(a.shape)
print(a.shape[0])  # accesssing the no of rows 
print(a.shape[1])  # accesssing the no of cols 

torch.Size([2, 3])
2
3


In [64]:
# if you want to build one same shape tensor 
copied_blank_tensor = torch.empty_like(a)
print(copied_blank_tensor)

print(torch.ones_like(a))
print(torch.zeros_like(a))

print(torch.rand_like(a,dtype=torch.float)) # giving errror without dtype specify

tensor([[-4.7566e+29,  1.7544e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])


In [59]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [61]:
# using to()
a.to(torch.float32)

tensor([[-4.7554e+29,  1.7544e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [65]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [74]:
# # add
a + b
# # sub
a - b
# # multiply
a * b
# # division
a / b
# # power
a ** b
# mod
a % b

tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])

In [77]:
# add
a+2

# sub
a-2

# mul
a*2

# div
a/2


tensor([[0.1119, 0.1512, 0.0892],
        [0.4119, 0.2779, 0.4885]])

In [ ]:
# absolute tensor
tensorr = torch.tensor([1.01,-1.98,-3.2, 25.0,0.0],dtype=torch.float)
print(tensorr)

tensor([ 1.0100, -1.9800, -3.2000, 25.0000,  0.0000])


In [81]:
print(torch.abs(tensorr))

tensor([ 1.0100,  1.9800,  3.2000, 25.0000,  0.0000])


In [82]:
# negative tensor 
print(torch.neg(tensorr))

tensor([ -1.0100,   1.9800,   3.2000, -25.0000,  -0.0000])


In [83]:
# round tensor 
print(torch.round(tensorr))

tensor([ 1., -2., -3., 25.,  0.])


In [84]:
# ceil 
print(torch.ceil(tensorr))

tensor([ 2., -1., -3., 25.,  0.])


In [86]:
# floor 
print(torch.floor(tensorr))

tensor([ 1., -2., -4., 25.,  0.])


In [87]:
# clamp 
print(torch.clamp(tensorr,min=0,max = 5))

tensor([1.0100, 0.0000, 0.0000, 5.0000, 0.0000])


In [88]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 0., 0.],
        [9., 5., 7.]])

In [89]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([ 7., 21.])

In [90]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([8.0000, 2.5000, 3.5000])

In [91]:
# median
torch.median(e)

tensor(5.)

In [94]:
# max and min
torch.max(e,dim=1)
torch.min(e)

tensor(0.)

In [95]:
# product
torch.prod(e)

tensor(0.)

In [96]:
# standard deviation
torch.std(e)

tensor(3.8297)

In [97]:
# variance
torch.var(e)

tensor(14.6667)

In [ ]:
# argmax
torch.argmax(e)  #giving the largest element position

tensor(3)

In [99]:
# argmin
torch.argmin(e)  #giving the min element position

tensor(1)

In [102]:
# matrix operation 
t1 = torch.randint(size=(3,2),low=1,high = 25)
t2 = torch.randint(size=(2,2),low=1,high= 25)
print(t1)
print("\n")
print(t2)

tensor([[ 7,  8],
        [16,  4],
        [ 1,  3]])


tensor([[18, 18],
        [ 7,  4]])


In [ ]:
# matrix multiplication

matProd = torch.matmul(t1,t2)
print(matProd)

tensor([[182, 158],
        [316, 304],
        [ 39,  30]])


In [104]:
# dot product 
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,2])

print(torch.dot(v1,v2))


tensor(7)


In [106]:
# transpose 

print(torch.transpose(t1,0,1))


tensor([[ 7, 16,  1],
        [ 8,  4,  3]])


In [112]:
# determinant 
square_t = torch.tensor([[3,2,2],[3,3,3],[1,19,8]],dtype=torch.float)
print(torch.det(square_t))

print(torch.inverse(square_t))

tensor(-33.0000)
tensor([[ 1.0000e+00, -6.6667e-01, -1.8062e-09],
        [ 6.3636e-01, -6.6667e-01,  9.0909e-02],
        [-1.6364e+00,  1.6667e+00, -9.0909e-02]])


In [3]:
# comparision operatios 
t3 = torch.randint(size=(2,2),low=1,high= 25,dtype=torch.float)
t4 = torch.randint(size=(2,2),low=1,high= 25)

print(t3)
print("\n")
print(t4)


tensor([[22., 12.],
        [ 1.,  7.]])


tensor([[5, 5],
        [9, 2]])


In [ ]:
print("greater than operation ")
print(t3>t4)

print("lesss than operation ")
print(t3<t4)

print("equal operation ")
print(t3 == t4)

greater than operation 
tensor([[True, True],
        [True, True]])
lesss than operation 
tensor([[False, False],
        [False, False]])
equal operation 
tensor([[False, False],
        [False, False]])


In [118]:
# log
torch.log(t4)

tensor([[2.8332, 3.1355],
        [2.3026, 1.9459]])

In [119]:
# exp
torch.exp(t4)

tensor([[2.4155e+07, 9.7448e+09],
        [2.2026e+04, 1.0966e+03]])

In [120]:
# sqrt
torch.sqrt(t4)

tensor([[4.1231, 4.7958],
        [3.1623, 2.6458]])

In [121]:
# sigmoid
torch.sigmoid(t4)

tensor([[1.0000, 1.0000],
        [1.0000, 0.9991]])

In [ ]:
# softmax
torch.softmax(t3, dim=1)   # here the tensor is needed in float dtype

tensor([[9.9995e-01, 4.5398e-05],
        [2.4726e-03, 9.9753e-01]])

In [5]:
# log 
torch.log(t4)

tensor([[1.6094, 1.6094],
        [2.1972, 0.6931]])

In [7]:
# relu 
torch.relu(t4)

tensor([[5, 5],
        [9, 2]])

INPLACE OPERATION

In [12]:
m = torch.randint(size=(2,3),high = 10, low =0)
n = torch.randint(size=(2,3),high = 10, low =0)
print(m)
print(n)

tensor([[1, 2, 5],
        [0, 1, 9]])
tensor([[3, 3, 9],
        [7, 2, 9]])


In [13]:
m.add_(n)

tensor([[ 4,  5, 14],
        [ 7,  3, 18]])

In [14]:
print(m)

tensor([[ 4,  5, 14],
        [ 7,  3, 18]])


In [18]:
# relu operation 
m.relu_()
m

tensor([[ 4,  5, 14],
        [ 7,  3, 18]])

In [ ]:
# copying tensor

b = a  
# in this case whenever you are doing changes in a then changes are also reflect in b also 
# in some cases you dont want to handle this setuation !

In [ ]:
t_copy = t4.clone()

print(id(t_copy))  #location of this 
print(id(t4))

2807600566256
2807600566336


Tensor operations on GPU

In [22]:
torch.cuda.is_available()

True

In [26]:
device = torch.device('cuda')
device

device(type='cuda')

In [27]:
# creating a new tensor on gpu 
t_on_gpu = torch.tensor([[1,2,3,4],[5,4,2,1],[9,8,7,6]],device=device,dtype = torch.float)

In [28]:
t_on_gpu.device

device(type='cuda', index=0)

In [32]:
# ṃoving on existing tensor to gpu 
t4.to(device=device)

tensor([[5, 5],
        [9, 2]], device='cuda:0')

tensor([[10, 10],
        [14,  7]])


In [41]:
import time 

# defining the size of the matrix 
size = 10000   # large size for performance comparision

# create random matrices on CPU 
matrix_cpu1=torch.randn(size,size)
matrix_cpu2= torch.randn(size,size)

# Measure time on CPU 
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time()-start_time

print(f"Time on CPU:{cpu_time:.4f} seconds")

# Move matrices to gpu 
matrix_gpu1 = matrix_cpu1.to("cuda") 
matrix_gpu2 = matrix_cpu2.to("cuda") 


# measure time on GPU 
start_time = time.time()
result_cpu = torch.matmul(matrix_gpu1,matrix_gpu2)

gpu_time = time.time() - start_time

print(f"total time on gpu {gpu_time}")



print(cpu_time/gpu_time)

Time on CPU:4.4191 seconds
total time on gpu 0.0025081634521484375
1761.877186311787


In [42]:
# reshaping tensors 
t_for_reshaping = torch.randint(size=(3,3,2),high = 25,low = 10)
t_for_reshaping

tensor([[[15, 11],
         [14, 12],
         [23, 12]],

        [[19, 12],
         [18, 10],
         [12, 23]],

        [[21, 24],
         [12, 19],
         [10, 17]]])

In [ ]:
t_for_reshaping.reshape(6,3)


tensor([[15, 11, 14],
        [12, 23, 12],
        [19, 12, 18],
        [10, 12, 23],
        [21, 24, 12],
        [19, 10, 17]])

In [50]:
# flattten
t_for_reshaping.flatten()

tensor([15, 11, 14, 12, 23, 12, 19, 12, 18, 10, 12, 23, 21, 24, 12, 19, 10, 17])

In [56]:
# permute 
t_for_permute = torch.rand(2,3,4)

t_for_permute.permute(2,0,1).shape # means now our tensor dimension is (2,3,4)->(4,2,3)
# t_for_permute.shape

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze its basically add dimension on specific position 
c = torch.rand(226,226,3)
c.unsqueeze(0).shape  # (1,226,226,3)


torch.Size([1, 226, 226, 3])

In [58]:
# numpy and PyTorch
import numpy as np 

a = torch.tensor([1,2,3])
b = a.numpy()
print(type(b))

<class 'numpy.ndarray'>


In [59]:
tensor_from_numpy = torch.from_numpy(b)
print(type(tensor_from_numpy))

<class 'torch.Tensor'>
