In [2]:
import torch
import warnings
import sys
import numpy as np
warnings.filterwarnings('ignore')
# Print versions
print("torch version:", torch.__version__)
print("numpy version:", np.__version__)
print("python version: ",sys.version)

torch version: 2.5.1+cu121
numpy version: 2.1.3
python version:  3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]


In [12]:
first_tensor = torch.tensor([[11,12,13],[14,15,16]],dtype=float,requires_grad=True)
print(first_tensor)
print(first_tensor.dtype)
print(first_tensor.requires_grad)
print(first_tensor.shape)

tensor([[11., 12., 13.],
        [14., 15., 16.]], dtype=torch.float64, requires_grad=True)
torch.float64
True
torch.Size([2, 3])


In [ ]:
second_tensor = torch.tensor([[1,9,8],[0,6,7]],requires_grad=True,dtype=float)


addition_tensor = first_tensor + second_tensor
print(addition_tensor)

substract_tensor = first_tensor - second_tensor
print(substract_tensor)

mul_tensor = first_tensor* second_tensor
print(mul_tensor)

divide_tensor = first_tensor/second_tensor
print(divide_tensor)

power_tensort = first_tensor**2
print("power tensor\n",power_tensort)

tensor([[12., 21., 21.],
        [14., 21., 23.]], dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([[10.,  3.,  5.],
        [14.,  9.,  9.]], dtype=torch.float64, grad_fn=<SubBackward0>)
tensor([[ 11., 108., 104.],
        [  0.,  90., 112.]], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([[11.0000,  1.3333,  1.6250],
        [    inf,  2.5000,  2.2857]], dtype=torch.float64,
       grad_fn=<DivBackward0>)
power tensor
 tensor([[121., 144., 169.],
        [196., 225., 256.]], dtype=torch.float64, grad_fn=<PowBackward0>)


In [16]:
print("shape of first tensor before reshaping :-",first_tensor.shape)
first_tensor.view(3,2)
reshaped_first_tensor = first_tensor.reshape(3,2)
print(reshaped_first_tensor)
print("shape of first tensor after reshaping :-",reshaped_first_tensor.shape)

shape of first tensor before reshaping :- torch.Size([2, 3])
tensor([[11., 12.],
        [13., 14.],
        [15., 16.]], dtype=torch.float64, grad_fn=<ViewBackward0>)
shape of first tensor after reshaping :- torch.Size([3, 2])


In [ ]:
# performing indexing 
shape = first_tensor.shape
for i in range(shape[0]):
    for j in range(shape[1]):
        print("this is the ",i,"th row element and ",j,"th column element",first_tensor[i][j])


this is the  0 th row element and  0 th column element tensor(11., dtype=torch.float64, grad_fn=<SelectBackward0>)
this is the  0 th row element and  1 th column element tensor(12., dtype=torch.float64, grad_fn=<SelectBackward0>)
this is the  0 th row element and  2 th column element tensor(13., dtype=torch.float64, grad_fn=<SelectBackward0>)
this is the  1 th row element and  0 th column element tensor(14., dtype=torch.float64, grad_fn=<SelectBackward0>)
this is the  1 th row element and  1 th column element tensor(15., dtype=torch.float64, grad_fn=<SelectBackward0>)
this is the  1 th row element and  2 th column element tensor(16., dtype=torch.float64, grad_fn=<SelectBackward0>)


In [22]:
# broadcasting
# Automatically expanding a smaller tensor so it can operate element-wise with a larger tensor, without copying data.
A = torch.tensor([[1, 2, 3],[4, 5, 6]])   
b = torch.tensor([10, 20, 30]) 
A + b


tensor([[11, 22, 33],
        [14, 25, 36]])

In [23]:
# que:3 :- write a program to perform and and or gate with the help of python 

x = [0,1]
y = [0,1]

# and gate :-
for i in x:
    for j in y:
        print("x value is ",i, "and y value is ",j,"and and gate value is " ,i*j)
        


x value is  0 and y value is  0 and and gate value is  0
x value is  0 and y value is  1 and and gate value is  0
x value is  1 and y value is  0 and and gate value is  0
x value is  1 and y value is  1 and and gate value is  1


In [24]:
x = [0,1]
y = [0,1]

# or gate :-
for i in x:
    for j in y:
        if(i+j):
            print("x value is ",i, "and y value is ",j,"and and gate value is 1 ")
        else:
            print("x value is ",i, "and y value is ",j,"and and gate value is 0 ")

        


x value is  0 and y value is  0 and and gate value is 0 
x value is  0 and y value is  1 and and gate value is 1 
x value is  1 and y value is  0 and and gate value is 1 
x value is  1 and y value is  1 and and gate value is 1 


In [ ]:
# que 4 : implimenting xor gate with the help of perceptron 

import torch.nn as nn

X = torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y = torch.tensor([[0.],[1.],[1.],[0.]])


model = nn.Sequential(
    nn.Linear(2, 2),
    nn.ReLU(),
    nn.Linear(2, 1),
    nn.Sigmoid()
)

loss_fn = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)


for _ in range(10000):
    y_pred = model(X)
    loss = loss_fn(y_pred, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(torch.round(model(X)))

tensor([[0.],
        [0.],
        [0.],
        [0.]], grad_fn=<RoundBackward0>)
