In [2]:
import torch
import warnings
import sys
import numpy as np
warnings.filterwarnings('ignore')
# Print versions
print("torch version:", torch.__version__)
print("numpy version:", np.__version__)
print("python version: ",sys.version)

torch version: 2.5.1+cu121
numpy version: 2.1.3
python version:  3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]


In [12]:
first_tensor = torch.tensor([[11,12,13],[14,15,16]],dtype=float,requires_grad=True)
print(first_tensor)
print(first_tensor.dtype)
print(first_tensor.requires_grad)
print(first_tensor.shape)

tensor([[11., 12., 13.],
        [14., 15., 16.]], dtype=torch.float64, requires_grad=True)
torch.float64
True
torch.Size([2, 3])


In [ ]:
second_tensor = torch.tensor([[1,9,8],[0,6,7]],requires_grad=True,dtype=float)


addition_tensor = first_tensor + second_tensor
print(addition_tensor)

substract_tensor = first_tensor - second_tensor
print(substract_tensor)

mul_tensor = first_tensor* second_tensor
print(mul_tensor)

divide_tensor = first_tensor/second_tensor
print(divide_tensor)

power_tensort = first_tensor**2
print("power tensor\n",power_tensort)

tensor([[12., 21., 21.],
        [14., 21., 23.]], dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([[10.,  3.,  5.],
        [14.,  9.,  9.]], dtype=torch.float64, grad_fn=<SubBackward0>)
tensor([[ 11., 108., 104.],
        [  0.,  90., 112.]], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([[11.0000,  1.3333,  1.6250],
        [    inf,  2.5000,  2.2857]], dtype=torch.float64,
       grad_fn=<DivBackward0>)
power tensor
 tensor([[121., 144., 169.],
        [196., 225., 256.]], dtype=torch.float64, grad_fn=<PowBackward0>)


In [16]:
print("shape of first tensor before reshaping :-",first_tensor.shape)
first_tensor.view(3,2)
reshaped_first_tensor = first_tensor.reshape(3,2)
print(reshaped_first_tensor)
print("shape of first tensor after reshaping :-",reshaped_first_tensor.shape)

shape of first tensor before reshaping :- torch.Size([2, 3])
tensor([[11., 12.],
        [13., 14.],
        [15., 16.]], dtype=torch.float64, grad_fn=<ViewBackward0>)
shape of first tensor after reshaping :- torch.Size([3, 2])


In [ ]:
# performing indexing 
shape = first_tensor.shape
for i in range(shape[0]):
    for j in range(shape[1]):
        print("this is the ",i,"th row element and ",j,"th column element",first_tensor[i][j])


this is the  0 th row element and  0 th column element tensor(11., dtype=torch.float64, grad_fn=<SelectBackward0>)
this is the  0 th row element and  1 th column element tensor(12., dtype=torch.float64, grad_fn=<SelectBackward0>)
this is the  0 th row element and  2 th column element tensor(13., dtype=torch.float64, grad_fn=<SelectBackward0>)
this is the  1 th row element and  0 th column element tensor(14., dtype=torch.float64, grad_fn=<SelectBackward0>)
this is the  1 th row element and  1 th column element tensor(15., dtype=torch.float64, grad_fn=<SelectBackward0>)
this is the  1 th row element and  2 th column element tensor(16., dtype=torch.float64, grad_fn=<SelectBackward0>)


In [22]:
# broadcasting
# Automatically expanding a smaller tensor so it can operate element-wise with a larger tensor, without copying data.
A = torch.tensor([[1, 2, 3],[4, 5, 6]])   
b = torch.tensor([10, 20, 30]) 
A + b


tensor([[11, 22, 33],
        [14, 25, 36]])

In [23]:
# que:3 :- write a program to perform and and or gate with the help of python 

x = [0,1]
y = [0,1]

# and gate :-
for i in x:
    for j in y:
        print("x value is ",i, "and y value is ",j,"and and gate value is " ,i*j)
        


x value is  0 and y value is  0 and and gate value is  0
x value is  0 and y value is  1 and and gate value is  0
x value is  1 and y value is  0 and and gate value is  0
x value is  1 and y value is  1 and and gate value is  1


In [24]:
x = [0,1]
y = [0,1]

# or gate :-
for i in x:
    for j in y:
        if(i+j):
            print("x value is ",i, "and y value is ",j,"and and gate value is 1 ")
        else:
            print("x value is ",i, "and y value is ",j,"and and gate value is 0 ")

        


x value is  0 and y value is  0 and and gate value is 0 
x value is  0 and y value is  1 and and gate value is 1 
x value is  1 and y value is  0 and and gate value is 1 
x value is  1 and y value is  1 and and gate value is 1 


In [ ]:
# que 4 : implimenting xor gate with the help of perceptron 

import torch.nn as nn

X = torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y = torch.tensor([[0.],[1.],[1.],[0.]])


model = nn.Sequential(
    nn.Linear(2, 2),
    nn.ReLU(),
    nn.Linear(2, 1),
    nn.Sigmoid()
)

loss_fn = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)


for _ in range(10000):
    y_pred = model(X)
    loss = loss_fn(y_pred, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(torch.round(model(X)))

tensor([[0.],
        [0.],
        [0.],
        [0.]], grad_fn=<RoundBackward0>)


In [8]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [ ]:
CSV_PATH = r"C:\Users\Lenovo\OneDrive\Desktop\deep Learning\assignments\one\house_price_full+(2) - house_price_full+(2).csv"

df = pd.read_csv(CSV_PATH)
df.head()



bedrooms  sqft_living    price
0         3         1340   313000
1         5         3650  2384000
2         3         1930   342000
3         3         2000   420000
4         4         1940   550000

In [10]:
X = df.iloc[:, :-1].values   
y = df.iloc[:, -1].values   


In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [12]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [13]:
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)

X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)


In [14]:
class HousePriceDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


In [15]:
train_dataset = HousePriceDataset(X_train, y_train)
test_dataset = HousePriceDataset(X_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)


In [16]:
class RegressionNet(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.net(x)


In [17]:
model = RegressionNet(X_train.shape[1])

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


In [19]:
epochs = 100

for epoch in range(epochs):
    model.train()
    total_loss = 0

    for X_batch, y_batch in train_loader:
        optimizer.zero_grad()
        preds = model(X_batch)
        loss = criterion(preds, y_batch)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    if (epoch + 1) % 10 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {total_loss:.4f}")


Epoch [10/100], Loss: 5821373284352.0000
Epoch [20/100], Loss: 5892135911424.0000
Epoch [30/100], Loss: 5955366256640.0000
Epoch [40/100], Loss: 5794195243008.0000
Epoch [50/100], Loss: 5693176741888.0000
Epoch [60/100], Loss: 5670970163200.0000
Epoch [70/100], Loss: 5496065736704.0000
Epoch [80/100], Loss: 5673649520640.0000
Epoch [90/100], Loss: 5510911950848.0000
Epoch [100/100], Loss: 5245815029760.0000


In [20]:
model.eval()
with torch.no_grad():
    predictions = model(X_test)
    test_loss = criterion(predictions, y_test)

print("Test MSE:", test_loss.item())


Test MSE: 264689696768.0
